### ISSUE TITLE
Ask Build on kernel 5.10

### ISSUE THREAD

**Issue by avinakefin** [dakkshesh07/Kprofiles#17]
Hi sir sorry if my ask is Weird 😅 , I found an error while building on kernel 5.10 marble device. And this error is show

../drivers/misc/kprofiles/main.c:85:30: error: implicit declaration of function 'kp_active_mode' [-Werror,-Wimplicit-function-declaration]
        unsigned int current_mode = kp_active_mode();
                                    ^
../drivers/misc/kprofiles/main.c:87:10: error: cast to 'void *' from smaller integer type 'unsigned int' [-Werror,-Wint-to-void-pointer-cast]
                                     (void *)current_mode);

How to fix this 🙏🏻

**Comment by dakkshesh07** [comment]
> Hi sir sorry if my ask is Weird 😅 , I found an error while building on kernel 5.10 marble device. And this error is show
> 
> ../drivers/misc/kprofiles/main.c:85:30: error: implicit declaration of function 'kp_active_mode' [-Werror,-Wimplicit-function-declaration] unsigned int current_mode = kp_active_mode(); ^ ../drivers/misc/kprofiles/main.c:87:10: error: cast to 'void *' from smaller integer type 'unsigned int' [-Werror,-Wint-to-void-pointer-cast] (void *)current_mode);
> 
> How to fix this 🙏🏻

May i know why are you trying to compile the staging branch? Its not stable yet and we are aware of the issues. Please refrain yourself from using the staging branch until its stable and merged to the main branch.
